
# 실행환경 세팅
spring:
  profiles:
    group:
      # 개발모드 프로파일
      dev: dev-env, common 
      # 배포모드 프로파일
      prod: prod-env, common
    
    # 실행 모드 설정 (dev 또는 prod로 설정)
    active: dev
    
---

# 개발 전용 프로파일
spring:
  config:
    activate:
      on-profile: dev-env
    
  # JPA 테이블은 항상 삭제 후 새로 생성
  jpa:
    hibernate:
      ddl-auto: create
    
---

# 배포 전용 프로파일
spring:
  config:
    activate:
      on-profile: prod-env
  
  # JPA 테이블 삭제 안함
  jpa:
    hibernate:
      ddl-auto: update

---

# 공통 프로파일
spring:
  config:
    activate:
      on-profile: common
  
  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      connection-timeout: 20000
      initialization-fail-timeout: -1
  data:
    mongodb:
      uri: ${MONGO_URI}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
     naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        format_sql: true
        show-sql: true

# 🔹 로깅 레벨 추가
logging:
  level:
    org.springframework.data.mongodb.core: TRACE
    org.mongodb.driver: INFO
    org.springframework.data.mongodb.core.MongoTemplate: TRACE

--- #jwt

jwt:
  secret-key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

sso:
  clientId:
    kakao: ${SSO_KAKAO_CLIENT_ID}
    google: ${SSO_GOOGLE_CLIENT_ID}
  callback:
    kakao: ${SSO_CALLBACK_URL}/kakao
    google: ${SSO_CALLBACK_URL}/google
  clientSecret:
    google: ${SSO_GOOGLE_SECRET}

# springdoc swagger
springdoc:
  api-docs:
    # false : Disabling the /v3/api-docs endpoint
    enabled: true
  swagger-ui:
    # false : Disabling the swagger-ui
    enabled: true